
# Just a work in progress version, not fully implemented. For conceptual purpose only.
# Need to add more steps and tested to make it functional fully. But this can be achieved.  

name: ci-windows-latest

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  build-docker-latest:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./rabbitmq/windows/latest
          push: true
          tags: micdenny/rabbitmq-windows:latest

  build-docker-38:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./rabbitmq/windows/3.8.35
          push: true
          tags: micdenny/rabbitmq-windows:3.8.35

  build-docker-39:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./rabbitmq/windows/3.9.22
          push: true
          tags: micdenny/rabbitmq-windows:3.9.22

  build-docker-310:
    runs-on: windows-2019
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./rabbitmq/windows/3.10.7
          push: true
          tags: micdenny/rabbitmq-windows:3.10.7